services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: "frostbot"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - frostbot-data:/var/lib/postgresql/data
    restart: unless-stopped
  rabbit:
    image: rabbitmq:4
    restart: unless-stopped
  lemontree:
    build: ./lemontree
    environment:
      BOT_TOKEN: "${LEMON_TREE_TOKEN}"
      DATABASE_URL: "postgresql://frostbot:${POSTGRES_PASSWORD}@db/frostbot"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      RABBIT_URL: "amqp://guest:guest@rabbit"
    restart: unless-stopped
    depends_on:
      - db
      - rabbit
  lucani:
    build: ./lucani
    environment:
      BOT_TOKEN: "${LUCANI_TOKEN}"
      DATABASE_URL: "postgresql://frostbot:${POSTGRES_PASSWORD}@db/frostbot"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
      RABBIT_URL: "amqp://guest:guest@rabbit"
    restart: unless-stopped
    depends_on:
      - db
      - rabbit

volumes:
  frostbot-data:
